### ISSUE TITLE
Project 1 Feedback

### ISSUE THREAD

**Issue by esin87** [mahletbogale/mahi_project_one#1]
# Project 1 Feedback

## Code Quality - Performing

Criteria: Is the code well-formatted? Are variable and function names semantic and sensible? Is the code easy to read and understand?

### Strengths:

- Code is (mostly) well-formatted with semantic and sensible naming throughout. 
- Code is easy to read and understand. 

### Areas for Growth:

- Both your CSS and HTML files through errors and warnings when passed through validators. Be sure to check those files before submitting projects next time. 
- Are your code editor's linter and formatting settings the same as what we set up on Day 1 of class? If not let me know and we can troubleshoot. Some of the formatting appears a bit inconsistent. 
- I noticed that the getPicture function is handled by brute force -- 26 `if` statements is a lot of code to write! How might you use a combination of event target ids and picture file naming to refactor, and make that a more dynamic (and less tiring) function to code? 

## Technical Requirements - Performing

Criteria: How does the project stack up to the requirements for this project? Is the developer making use of the material we've covered in a way that makes sense?

### Strengths:

- Your application meets all the technical requirements listed below! The app renders in the browser and no errors were observed in the console. Nice job getting your app deployed to GH Pages, and also having a good history of commits dating back to the start of your project. 
- Nice job implementing the material we covered in class and synthesizing it into a unique application.

### Areas for Growth:

- Modern web applications tend not to have multiple HTML files. I would recommend trying to incorporate the landing screen into the index.html and going back and forth between the two using DOM manipulation, not navigating between different HTML files. 
- I was not able to see if you worked on a a development branch. For further feature development and for future projects, be sure to make use of Git Branches to work on code without affecting the master branch -- this will keep you from having to worry about breaking the working application, and is a useful development practice to get in the habit of doing. 
- GitHub repo shows a good history of commits, but work on the consistency of your commit message formatting and content. The standard is usually 'capitalized present-tense verb + description of what was done' for each and every commit. For example, 'Add styling to gameboard container' or 'Refactor API call'. [This](https://chris.beams.io/posts/git-commit/) is my favorite article on how to write good commit messages and why it's an important focus for developers.

## Creativity and Interface - Performing

Criteria: Is the application easy to navigate? Does it work well in every major browser? Is it responsive? Does it incorporate modern UI Themes?

### Strengths:

- App is easy to navigate and use. It displays well in Chrome and Safari, but there is a white outline for the card that shows up on the Safari browser. 
- UI is straightforward, simple and attractively designed. Responsive to smaller screen sizes and wider as well! Nice job working out those media queries to get your app responsive. 

### Areas for Growth

- Some of the pictures appear a bit skewed in terms of their ratio. How could you adjust the styling to make sure that the images fill their container, but aren't stretched in any way? 

## Functionality - Performing

Criteria: Does the application work without errors or bugs? Does it present a complete app, where every feature is fully implemented in a way that makes sense?

### Strengths:

- The application works without any errors or bugs observed. 
- Application presents a complete game, with user feedback and the option to start over. Features are fully implemented. 

### Areas for Growth:

- Currently the first page we see is `index.html`, though I know you built out a landing page. The index is usually the default page in a web application, which is why it's navigating there automatically. Consolidating your code into one HTML document would prevent this issue, and you could better control what is shown on the landing page and give the user the option to start the game.  

## Presentation - Progressing

Criteria: Is there adequate documentation? Is the repository well organized and free of clutter?

### Strengths:

- The README is off to a good start with a detailed description, and highlights parts of your planning process including your wireframes and user stories. This is the first point of contact to your application, and does a good job of introducing your application to the world. 
- The repo is overall well-organized and free of clutter, other than the multiple HTML files, which I hope you consolidate. 

### Areas for Growth:

- The README is not populating on your repository because there is a typo in its spelling. It should be called `README.MD`, not `README.ME`. 
- The README needs to be further developed and include the following: screenshots of major views, contribution guidelines, installation instructions, unsolved problems (if any). 
- The About panel on the right side of your repo should include a very brief description of your application as well as the URL of your deployed site. 

![URL section](https://media.giphy.com/media/WUsOlSNbPlE72OudJs/giphy.gif) 

## Hard Requirements - Complete:

- [x] Render in the browser
- [x] Include separate HTML / CSS / JavaScript files
- [x] Use Javascript for DOM manipulation
- [x] Be deployed online, using Github Project pages and/or to a custom domain.
- [x] Use semantic markup for HTML and CSS (adhere to best practices)
- [x] Show a good commit history with frequent commits

## Necessary Deliverables - (Almost) Complete: 
- [x] A hosted copy of your game, built by you, hosted on Github Pages
- [ ] Your HTML/CSS should pass the HTML5 Validator and CSS Validator ❌  -- please be sure to run your code through the validators and fix the warnings/errors 
- [x] A git repository hosted on Github with frequent commits dating back to the very beginning of the project
- [ ] A link to your hosted project in the URL section of your Github repo  ❌  -- this is a quick fix
- [x] A readme.md file, including explanations of the technologies used, the approach taken, installation instructions, unsolved problems, etc. -- you do have a README, but make sure the file extension is correct and continue to build it out so that it is an engaging first point of contact for visitors to your repo

## Grade: Pass  🎉🎉🎉 

Mahlet, excellent work on your first project! You created a visually pleasing, engaging application that is highly functional, all in the span of a week-long sprint. Your code highlights many of the key ideas that we learned in the frontend unit, and does a great job of bringing them together in an application that I know would be a great asset for all the parents with children at home right now! Do take a look at some of my suggestions and work on refining your application, and attaining some of those silver- and gold-level goals that you have. Thank you for your hard work on this project and throughout our class, and I look forward to seeing your continued success in the course. As always, please let me know if you have any questions or concerns about this or anything else!

**Comment by mahletbogale** [comment]
Thanks for the feedback Esin,it is an encouraging one and i will keep up
the good work
